on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'release')
    steps:
#      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.4
      - name: Init environment
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root
#      - name: Check coding standards
#        run: |
#          set -euo pipefail
#          source $HOME/.poetry/env
#          poe flake8
#          poe black-check
      - name: Build package
        run: |
          poetry build --format wheel
      - name: Publish package to pypi.org
        run: |
          poetry publish --username "__token__" --password ${{ secrets.PYPI_API_TOKEN }}
